### ISSUE TITLE
Publish the tool so it can be used by application developers

### ISSUE THREAD

**Issue by tjololo** [Altinn/altinn-studio-cli#5]
### Description

This tool needs to be exposed in a way that makes it easy for application developers to use it on their development machines.

### Tasks

- [ ] Create release and deployment action
- [ ] Document how to download/install/use

### Acceptance Criterias

- [ ] Tool made available for application developers to run locally on their development machine
- [ ] Use of the tool is documented
